name: weatherify
description: "Not any weather app, but the weather app you need."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  geolocator: ^14.0.2
  http: ^1.4.0
  weather_animation: ^1.1.2
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  icons_launcher: ^3.0.1
  rename: ^3.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env

icons_launcher:
  image_path: "assets/images/logo.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true